## THIS IS A CPP COMPILE TEMPLATE Makefile ##
# CFLAGS?= -pedantic -O2 -Wall -DNEBUG -W
# CFLAGS?= -pedantic -O0 -W -DDEBUG -g
CC = g++

VPATH=include:src:tests
SOURCE=src/
TESTPATH=tests/
TMPPATH=tmp/
INSTALLPATH=/usr/bin/

TARGET=
TESTS=
TARGETOBJS=
TESTSOBJS=

ALL:$(TARGET) $(TEST)
	make tidy
$(TARGET): ${TARGETOBJS}
$(TEST): $(TESTSOBJS)

tidy:
	mv ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} ${TMPPATH}
install:
	cp -rf ${TARGET} ${INSTALLPATH}
uninstall:
	cd ${INSTALLPATH} && rm -rf ${TARGET}

test: $(TARGET)
	@./${TARGET}
check: test
exec: test
e: test

clean:
	rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
	cd ${TEMP_PATH} && rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
clear: clean

dep:
	$(CC) -MM ${SOURCE}*.c ${SOURCE}*.cpp
.PHONY: tidy install uninstall test check exec e clean clear dep
## THIS IS A CPP COMPILE TEMPLATE Makefile ##
# CFLAGS?= -pedantic -O2 -Wall -DNEBUG -W
# CFLAGS?= -pedantic -O0 -W -DDEBUG -g
CC = g++

VPATH=include:src:tests
SOURCE=src/
TESTPATH=tests/
TMPPATH=tmp/
INSTALLPATH=/usr/bin/

TARGET=
TESTS=
TARGETOBJS=
TESTSOBJS=

ALL:$(TARGET) $(TEST)
	make tidy
$(TARGET): ${TARGETOBJS}
$(TEST): $(TESTSOBJS)

tidy:
	mv ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} ${TMPPATH}
install:
	cp -rf ${TARGET} ${INSTALLPATH}
uninstall:
	cd ${INSTALLPATH} && rm -rf ${TARGET}

test: $(TARGET)
	@./${TARGET}
check: test
exec: test
e: test

clean:
	rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
	cd ${TEMP_PATH} && rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
clear: clean

dep:
	$(CC) -MM ${SOURCE}*.c ${SOURCE}*.cpp
.PHONY: tidy install uninstall test check exec e clean clear dep
## THIS IS A CPP COMPILE TEMPLATE Makefile ##
# CFLAGS?= -pedantic -O2 -Wall -DNEBUG -W
# CFLAGS?= -pedantic -O0 -W -DDEBUG -g
CC = g++

VPATH=include:src:tests
SOURCE=src/
TESTPATH=tests/
TMPPATH=tmp/
INSTALLPATH=/usr/bin/

TARGET=
TESTS=
TARGETOBJS=
TESTSOBJS=

ALL:$(TARGET) $(TEST)
	make tidy
$(TARGET): ${TARGETOBJS}
$(TEST): $(TESTSOBJS)

tidy:
	mv ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} ${TMPPATH}
install:
	cp -rf ${TARGET} ${INSTALLPATH}
uninstall:
	cd ${INSTALLPATH} && rm -rf ${TARGET}

test: $(TARGET)
	@./${TARGET}
check: test
exec: test
e: test

clean:
	rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
	cd ${TEMP_PATH} && rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
clear: clean

dep:
	$(CC) -MM ${SOURCE}*.c ${SOURCE}*.cpp
.PHONY: tidy install uninstall test check exec e clean clear dep
## THIS IS A CPP COMPILE TEMPLATE Makefile ##
# CFLAGS?= -pedantic -O2 -Wall -DNEBUG -W
# CFLAGS?= -pedantic -O0 -W -DDEBUG -g
CC = g++

VPATH=include:src:tests
SOURCE=src/
TESTPATH=tests/
TMPPATH=tmp/
INSTALLPATH=/usr/bin/

TARGET=
TESTS=
TARGETOBJS=
TESTSOBJS=

ALL:$(TARGET) $(TEST)
	make tidy
$(TARGET): ${TARGETOBJS}
$(TEST): $(TESTSOBJS)

tidy:
	mv ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} ${TMPPATH}
install:
	cp -rf ${TARGET} ${INSTALLPATH}
uninstall:
	cd ${INSTALLPATH} && rm -rf ${TARGET}

test: $(TARGET)
	@./${TARGET}
check: test
exec: test
e: test

clean:
	rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
	cd ${TEMP_PATH} && rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
clear: clean

dep:
	$(CC) -MM ${SOURCE}*.c ${SOURCE}*.cpp
.PHONY: tidy install uninstall test check exec e clean clear dep
## THIS IS A CPP COMPILE TEMPLATE Makefile ##
# CFLAGS?= -pedantic -O2 -Wall -DNEBUG -W
# CFLAGS?= -pedantic -O0 -W -DDEBUG -g
CC = g++

VPATH=include:src:tests
SOURCE=src/
TESTPATH=tests/
TMPPATH=tmp/
INSTALLPATH=/usr/bin/

TARGET=
TESTS=
TARGETOBJS=
TESTSOBJS=

ALL:$(TARGET) $(TEST)
	make tidy
$(TARGET): ${TARGETOBJS}
$(TEST): $(TESTSOBJS)

tidy:
	mv ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} ${TMPPATH}
install:
	cp -rf ${TARGET} ${INSTALLPATH}
uninstall:
	cd ${INSTALLPATH} && rm -rf ${TARGET}

test: $(TARGET)
	@./${TARGET}
check: test
exec: test
e: test

clean:
	rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
	cd ${TEMP_PATH} && rm -rf ${TARGET} ${TESTS} ${TARGETOBJS} ${TESTSOBJS} *.o
clear: clean

dep:
	$(CC) -MM ${SOURCE}*.c ${SOURCE}*.cpp
.PHONY: tidy install uninstall test check exec e clean clear dep
